--- #YAML:1.0
name:                Template-Plugin-DumbQuotes
version:             0.01
abstract:            Transform educated quotes to dumb quotes
license:             ~
author:              
    - Yann Kerhervé <yannk@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.40
distribution_type:   module
requires:     
    Encode:                        0
    Template:                      0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
